from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path


async def login_and_save(cookie_path: Path, qr_path: Path, timeout: int = 180) -> None:
    """Log in with Bilibili's QR flow without touching browser data."""
    from bilibili_api.login_v2 import QrCodeLogin, QrCodeLoginEvents

    login = QrCodeLogin()
    await login.generate_qrcode()
    qr_path.parent.mkdir(parents=True, exist_ok=True)
    login.get_qrcode_picture().to_file(str(qr_path))
    print(login.get_qrcode_terminal(), flush=True)
    print(f"QR_IMAGE={qr_path}", flush=True)
    print("Scan the QR code with the Bilibili app and confirm the login.", flush=True)
    deadline = asyncio.get_running_loop().time() + timeout
    previous = None
    while asyncio.get_running_loop().time() < deadline:
        state = await login.check_state()
        if state != previous:
            print(f"LOGIN_STATE={state.value}", flush=True)
            previous = state
        if state == QrCodeLoginEvents.DONE:
            _write_netscape_cookies(cookie_path, login.get_credential().get_cookies())
            print(f"COOKIE_FILE={cookie_path}", flush=True)
            return
        if state == QrCodeLoginEvents.TIMEOUT:
            raise TimeoutError("The QR code has expired")
        await asyncio.sleep(2)
    raise TimeoutError("Timed out while waiting for QR code login")


def _write_netscape_cookies(path: Path, cookies: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by video2knowledge QR login"]
    for name, value in cookies.items():
        if value and name != "proxy":
            lines.append(f".bilibili.com\tTRUE\t/\tTRUE\t2147483647\t{name}\t{value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


def bili_dl_login_and_save(bili_dl_dir: Path, cookie_path: Path, download_dir: Path) -> Path:
    """Run bili-dl's own QR scanner and persist its native config."""
    if not (bili_dl_dir / "bili_dl" / "utils" / "login_helper.py").exists():
        raise FileNotFoundError(f"Invalid bili-dl directory: {bili_dl_dir}")
    sys.path.insert(0, str(bili_dl_dir))
    try:
        from bili_dl.config import ConfigManager
        from bili_dl.utils.login_helper import apply_credential, qr_login

        data_dir = bili_dl_dir / "data"
        manager = ConfigManager(str(data_dir))
        config = manager.load()
        config.download_dir = str(download_dir)
        config.max_concurrent = 1
        credential = qr_login()
        if not credential:
            raise TimeoutError("The bili-dl QR code login did not finish")
        apply_credential(config, credential)
        manager.save(config)
        _write_netscape_cookies(
            cookie_path,
            {
                "SESSDATA": credential.get("sessdata", ""),
                "bili_jct": credential.get("bili_jct", ""),
                "buvid3": credential.get("buvid3", ""),
                "DedeUserID": credential.get("dedeuserid", ""),
                "ac_time_value": credential.get("ac_time_value", ""),
            },
        )
        return data_dir / "config.json"
    finally:
        sys.path.remove(str(bili_dl_dir))
